### ISSUE TITLE
$t-variable in templates not working

### ISSUE THREAD

**Issue by jeffreyvanhees** [eLod/li3_mailer#10]
Hey guys,

Can you add support for g11n in templates? I would love to see this feature :)

Jeffrey

**Comment by eLod** [comment]
hey @fancenl. the thing is with g11n helpers is that they are added to view rendering via config initializers, you can check [here](https://github.com/UnionOfRAD/framework/blob/master/app/config/bootstrap/g11n.php#L215). the good news is that you should be able to add those helpers to mail rendering just the same (adding to `li3_mailer\net\mail\Media`).

**Comment by fancenl** [comment]
Met vriendelijke groeten,

Jeffrey van Hees - Fance.nl <http://fance.nl/> Web Development
jeffrey@fance.nl - www.fance.nl - 06 289 309 74

Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Fance.nl staat door de elektronische verzending van dit bericht niet in voor de juiste en volledige overbrenging van de inhoud, noch voor tijdige ontvangst daarvan. Voor informatie over Fance.nl raadpleegt u www.fance.nl.

**Comment by jeffreyvanhees** [comment]
Thanks @eLod for the quick response. Unfortunately, when I add the following code to the li3_mailer's media.php, I got an error:

```
# li3_mailer\net\mail\Media
Media::applyFilter('_handle', function($self, $params, $chain) {
    $params['handler'] += array('outputFilters' => array());
    $params['handler']['outputFilters'] += \lithium\g11n\Message::aliases(); // Added full namespace because Message is already in use by the library itself
    return $chain->next($self, $params, $chain);
});
```

`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Locale `` could not be parsed.' in /var/www/production/libraries/lithium/g11n/Locale.php:131`

So, how can I take care of the fact that Lithium will use the current locale-configuration?

**Comment by eLod** [comment]
hey @fancenl. i think you need to set the locale as well if you are rendering emails outside of the request-response cycle, e.g. you see the initializer applying the locale setter [here](https://github.com/UnionOfRAD/framework/blob/master/app/config/bootstrap/g11n.php#L58). also i think you don't need to use the the full path for `Message` because of the explicit import in that initializer file, where have you added your code? i would add it in that same initializer, and `use li3_mailer\net\mail\Media as MailMedia;`.

**Comment by jeffreyvanhees** [comment]
@eLod I've added the code just at the end of the file outside the class. If I do not use the full path for `Message` I got the error:
`Fatal error: Call to undefined method li3_mailer\net\mail\Message::aliases()`

So I did `use lithium\g11n\Message as MailMessage;` and the top of the file and changed my code to:

```
MailMedia::applyFilter('_handle', function($self, $params, $chain) {
    $params['handler'] += array('outputFilters' => array());
    $params['handler']['outputFilters'] += MailMessage::aliases();
    return $chain->next($self, $params, $chain);
});
```

and below the code above:

```
$setLocale = function($self, $params, $chain) {
    if (!$params['request']->locale()) {
        $params['request']->locale(Locale::preferred($params['request']));
    }
    Environment::set(true, array('locale' => $params['request']->locale()));

    return $chain->next($self, $params, $chain);
};

MailMedia::applyFilter('_handle', $setLocale);
```

This gives a new error:
`Notice: Undefined index: request in /var/www/production/libraries/li3_mailer/net/mail/Media.php on line 424`
and 
`Fatal error: Call to a member function locale() on a non-object in /var/www/production/libraries/li3_mailer/net/mail/Media.php on line 424`

So I think that lithium cannot find the right locale because there is no request-object.

(I'm sorry, I'm trying to understand MVC & Lithium and I'm not an expert yet ;-))

**Comment by eLod** [comment]
@fancenl strange, i dont think you should use `MailMessage` though, i would pass the class to the anonymous function via using. For the new error: yes, there is no `$params['request']` just remove those lines and set whatever locale you want to.

**Comment by jeffreyvanhees** [comment]
A few months later; it is working by adding:

```
use lithium\g11n\Message;
use li3_mailer\net\mail\Media;

Media::applyFilter('_handle', function($self, $params, $chain) {
    $params['handler'] += array('outputFilters' => array());
    $params['handler']['outputFilters'] += Message::aliases();
    return $chain->next($self, $params, $chain);
});
```

Thank you!
