### ISSUE TITLE
Setting the subject from inside a template

### ISSUE THREAD

**Issue by mariuswilms** [eLod/li3_mailer#11]
It'd be really great if we'd able to set the mail's subject from inside the template similar to what `$this->title()` does for regular templates. That would allow us to have all the wording inside the template.

**Comment by eLod** [comment]
@davidpersson i think it should work, i mean there should be a [title handler](https://github.com/eLod/li3_mailer/blob/master/template/mail/adapter/File.php#L146). I haven't touched this code for a while, so i may be missing something.

edit: so, i think i misunderstood your comment a bit. the title method i linked to just works the same way as in original lithium (stores your string and escapes when displayed, but you have to call it yourself, e.g. in your layout). for setting the message's subject simply do `$this->message()->subject('My subject');` in your template.

edit2: i also wanted to explicitly mention that you have to be very careful with this, if your message has multiple templates you should set the subject only in one. see notes at the end of https://raw.githubusercontent.com/eLod/li3_mailer/master/readme.wiki

**Comment by mariuswilms** [comment]
Thanks for the thorough explanation. I should've just read the README until the end...
