### ISSUE TITLE
Generating absolute URLs

### ISSUE THREAD

**Issue by mehlah** [eLod/li3_mailer#4]
While this isn't a specific issue to `li3_mailer`, this lib could bring a first solution.

When dealing with emails, one would generate absolute URLs and avoid using relative ones URLs.
Calling `Router::match()` with an `'absolute' => true` option do it, but sending emails from a li3 command break request environment and especially, the base host.

li3_mailer could expose a way to set the default host that will be used in all mailers.

PS: I ended up with doing a `Environment::set('production' => $config)`during the app bootstrap process

**Comment by eLod** [comment]
It is already doing `'absolute' => true` for the url helper [in the template](https://github.com/eLod/li3_mailer/blob/master/template/mail/adapter/File.php#L100), so i think that should already be working. Furthermore the message has a `$base_url` variable which can be configured from the bootstrap file which should be the host used for generating the absolute urls (also i think it's mentioned in the readme.wiki), see for example [this test](https://github.com/eLod/li3_mailer/blob/master/tests/cases/template/mail/adapter/FileTest.php#L40).

**Comment by mehlah** [comment]
Awesome :)
